import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/utilis/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Recycle Nepal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.svg" />
      <Providers>
        <body className={inter.className}>{children}</body>
      </Providers>
    </html>
  );
}
