
import { Inter } from 'next/font/google'
import './globals.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Recycle Nepal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <link rel="icon" href='/favicon.svg' />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
